"""Library artifact listing and retrieval endpoints."""

from __future__ import annotations

from typing import Any

from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel

router = APIRouter()


class ArtifactInfo(BaseModel):
    id: str
    run_id: str
    skill_id: str
    artifact_type: str
    title: str
    subtitle: str | None = None
    subject_type: str | None = None
    subject_id: str | None = None
    subject_name: str | None = None
    status: str
    summary: str | None = None
    content_markdown: str | None = None
    payload: dict[str, Any] = {}
    tags: list[str] = []
    created_at: str
    updated_at: str


@router.get("/artifacts", response_model=list[ArtifactInfo])
async def list_artifacts(
    request: Request,
    limit: int = 50,
    offset: int = 0,
    skill_id: str | None = None,
    artifact_type: str | None = None,
    subject_type: str | None = None,
    subject_id: str | None = None,
    run_id: str | None = None,
    q: str | None = None,
):
    """List Library artifacts with optional filters and pagination."""
    rows = request.app.state.db.list_artifacts(
        limit=limit,
        offset=offset,
        skill_id=skill_id,
        artifact_type=artifact_type,
        subject_type=subject_type,
        subject_id=subject_id,
        run_id=run_id,
        q=q,
    )
    return [ArtifactInfo(**row) for row in rows]


@router.get("/artifacts/{artifact_id}", response_model=ArtifactInfo)
async def get_artifact(request: Request, artifact_id: str):
    """Get a single Library artifact."""
    row = request.app.state.db.get_artifact(artifact_id)
    if not row:
        raise HTTPException(status_code=404, detail="Artifact not found")
    return ArtifactInfo(**row)


@router.get("/artifacts/{artifact_id}/versions")
async def list_artifact_versions(request: Request, artifact_id: str):
    """List historical snapshots of an artifact (newest version first).

    Snapshots are captured each time :meth:`Database.save_artifact` overwrites
    an existing artifact, so the Library can show how a report evolved across
    re-runs. Returns 404 if the artifact does not exist.
    """
    db = request.app.state.db
    if db.get_artifact(artifact_id) is None:
        raise HTTPException(status_code=404, detail="Artifact not found")
    return db.list_artifact_versions(artifact_id)


@router.get("/runs/{run_id}/artifacts", response_model=list[ArtifactInfo])
async def list_run_artifacts(request: Request, run_id: str):
    """List artifacts generated by a run."""
    rows = request.app.state.db.list_artifacts_for_run(run_id)
    return [ArtifactInfo(**row) for row in rows]
